# Generated by Django 4.0.5 on 2022-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carrito_producto_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carrito_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
