# Generated by Django 4.0.5 on 2022-06-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_imagen'),
        ('carrito', '0002_rename_producto_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carrito_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
            preserve_default=False,
        ),
    ]
