# Generated by Django 4.0.5 on 2022-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_imagen'),
        ('carrito', '0003_carrito_carrito_id_remove_carrito_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
