# Generated by Django 4.0.5 on 2022-06-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_carritoproductos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproductos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
