# Generated by Django 4.0.5 on 2022-06-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_carrito_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
    ]
