# Generated by Django 4.0.5 on 2022-06-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_carritoproductos_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
