# Generated by Django 4.0.5 on 2022-06-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_carrito_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
    ]
