# Generated by Django 4.0.5 on 2022-06-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/usuarios')),
                ('vendedor', models.BooleanField(default=False)),
                ('suscrito', models.BooleanField(default=False)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.region'),
        ),
    ]
