# Generated by Django 4.0.5 on 2022-07-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_comuna_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
