# Generated by Django 4.0.5 on 2022-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='personas'),
        ),
    ]
