# Generated by Django 4.0.6 on 2022-07-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfilusuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='suscrito',
        ),
    ]
