# Generated by Django 4.0.5 on 2022-06-13 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0004_alter_carritoproductos_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(ordenes.models.OrdenesStatus['CREADO'], 'CREADO'), (ordenes.models.OrdenesStatus['PAGADO'], 'PAGADO'), (ordenes.models.OrdenesStatus['COMPLETADO'], 'COMPLETADO'), (ordenes.models.OrdenesStatus['CANCELADO'], 'CANCELADO')], default=ordenes.models.OrdenesStatus['CREADO'], max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
