# Generated by Django 4.0.5 on 2022-06-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_ordenes_direccion_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
