# Generated by Django 4.0.5 on 2022-06-15 14:25

from django.db import migrations, models
import ordenes.common


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_ordenes_direccion_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='status',
            field=models.CharField(choices=[(ordenes.common.OrdenesStatus['CREADO'], 'CREADO'), (ordenes.common.OrdenesStatus['PAGADO'], 'PAGADO'), (ordenes.common.OrdenesStatus['COMPLETADO'], 'COMPLETADO'), (ordenes.common.OrdenesStatus['CANCELADO'], 'CANCELADO'), (ordenes.common.OrdenesStatus['EMPAQUETADO'], 'EMPAQUETADO'), (ordenes.common.OrdenesStatus['DESPACHADO'], 'DESPACHADO')], default=ordenes.common.OrdenesStatus['CREADO'], max_length=50),
        ),
    ]
